### ISSUE TITLE
Configuration locks up in Wine

### ISSUE THREAD

**Issue by pinobatch** [jimbo1qaz/0CC-FamiTracker#10]
When I try to open Configuration to change the buffer length and keymap, I get the [same lockup as on 0CC 0.3.14.5](http://hertzdevil.info/forum/index.php/topic,17.msg34.html#msg34).

Steps to repro:

1. Install Debian 9 "Stretch" (64-bit)
2. Save the [registry extract posted by B00daW](http://hertzdevil.info/forum/index.php/topic,17.msg31.html#msg31) as 0CC-FT.reg
3. `sudo apt install wine`
4. `wine --version` which should give `wine-1.8.7 (Debian 1.8.7-2)`
5. `wine regedit 0CC-FT.reg`
6. `wine 0CC-FamiTracker-j0.0.1.exe`

Result: Lockup; task needs to be killed

Expected: Configuration opens

**Comment by jimbo1qaz** [comment]
fixed in 7019189b182063e10c8da4487435dc57a1efaa1
