### ISSUE TITLE
Instrument editor locks up in Wine

### ISSUE THREAD

**Issue by pinobatch** [jimbo1qaz/0CC-FamiTracker#11]
When I try to make an instrument in your 0CC mod in Wine, I get the [same lockup as on 0CC-FT 0.3.14.5](http://hertzdevil.info/forum/index.php/topic,26.msg44.html#msg44).

Steps to repro:

1. Install Debian 9 "Stretch" (64-bit)
2. Save the [registry extract posted by B00daW](http://hertzdevil.info/forum/index.php/topic,17.msg31.html#msg31) as 0CC-FT.reg
3. `sudo apt install wine`
4. `wine --version` which should give `wine-1.8.7 (Debian 1.8.7-2)`
5. `wine regedit 0CC-FT.reg`
6. `wine 0CC-FamiTracker-j0.0.1.exe`
7. New 2A03 instrument
8. Double-click to open it
9. Under Instrument settings click Duty / Noise

Result: "Size: - 0 +" and "16 steps" blink, and nothing else responds to a click, until I terminate the process.

Occasionally in vanilla FT 0.4.6, I see them blinking for a short time, but it always resolves there.

**Comment by jimbo1qaz** [comment]
https://bugs.winehq.org/show_bug.cgi?id=40416
