### ISSUE TITLE
Reset VRC6 Phase

### ISSUE THREAD

**Issue by lindarthebard** [jimbo1qaz/0CC-FamiTracker#69]
https://wiki.nesdev.com/w/index.php/VRC6_audio#Pulse_Channels
There's a way to reset the phase of a VRC6 pulse channel.
I would very much like to be able to do that in order to create repeatable phase effects between the two pulse channels. Currently the phase doesn't reset between notes, so the phase gradually drifts, meaning the phasing effect is unpredictable on successive repetitions.

**Comment by lindarthebard** [comment]
0cc for now, but NSF export would be great. Thanks!

**Comment by todidodido** [comment]
Oh, that would be so cool if possible. You can make so much neat stuff with phasing, especially in the lower register. That's how you make "reese" bass for example.

**Comment by jimbo1qaz** [comment]
oh, 2 people want this? I may implement it sooner rather than later.

**Comment by jimbo1qaz** [comment]
unfinished https://github.com/jimbo1qaz/0CC-FamiTracker/pull/81 ......

**Comment by jimbo1qaz** [comment]
https://wiki.nesdev.com/w/index.php/VRC6_audio#Pulse_Channels

> When the channel is disabled by clearing the E bit, output is forced to 0, and the duty cycle is immediately reset and halted; it will resume from the beginning when E is once again set. Thus it is possible to reset phase by clearing and immediately setting E.

I tried that, but it seems FT's emulation doesn't handle that behavior or something

**Comment by jimbo1qaz** [comment]
Fixed VRC6 phase reset, implementation based off nsfplay code.

Can you test the build at https://ci.appveyor.com/api/buildjobs/hf0flkt0nf345jsk/artifacts/Release%2Fj0CC-PR81-phase-reset-build59.exe ?

Phase reset is `=00` and only supported on VRC6. Right now, `=xx` (where xx is not 0) shows up as red, but still performs phase reset. Should I change it to become a no-op effect?

**Comment by jimbo1qaz** [comment]
hello?

**Comment by jimbo1qaz** [comment]
Fixed in https://github.com/jimbo1qaz/0CC-FamiTracker/pull/81
